-- Copyright (c) 2024, Oracle and/or its affiliates.
-- Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
-- 
--     https://www.apache.org/licenses/LICENSE-2.0
-- 
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.

-- Secondary Load into HeatWave
ALTER TABLE CALL_CENTER SECONDARY_LOAD ;
ALTER TABLE CATALOG_PAGE SECONDARY_LOAD ;
ALTER TABLE CATALOG_RETURNS SECONDARY_LOAD ;
ALTER TABLE CATALOG_SALES SECONDARY_LOAD ;
ALTER TABLE HOUSEHOLD_DEMOGRAPHICS SECONDARY_LOAD ;
ALTER TABLE INCOME_BAND SECONDARY_LOAD ;
ALTER TABLE INVENTORY SECONDARY_LOAD ;
ALTER TABLE PROMOTION SECONDARY_LOAD ;
ALTER TABLE REASON SECONDARY_LOAD ;
ALTER TABLE SHIP_MODE SECONDARY_LOAD ;
ALTER TABLE STORE SECONDARY_LOAD ;
ALTER TABLE STORE_RETURNS SECONDARY_LOAD ;
ALTER TABLE STORE_SALES SECONDARY_LOAD ;
ALTER TABLE WAREHOUSE SECONDARY_LOAD ;
ALTER TABLE WEB_PAGE SECONDARY_LOAD ;
ALTER TABLE WEB_RETURNS SECONDARY_LOAD ;
ALTER TABLE WEB_SALES SECONDARY_LOAD ;
ALTER TABLE WEB_SITE SECONDARY_LOAD ;
ALTER TABLE CUSTOMER SECONDARY_LOAD ;
ALTER TABLE CUSTOMER_ADDRESS SECONDARY_LOAD ;
ALTER TABLE CUSTOMER_DEMOGRAPHICS SECONDARY_LOAD ;
ALTER TABLE DATE_DIM SECONDARY_LOAD ;
ALTER TABLE ITEM SECONDARY_LOAD ;
ALTER TABLE TIME_DIM SECONDARY_LOAD ;
